import { ArrowUpRight, FileSearch, Scale, ShieldCheck } from "lucide-react"

import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion"
import { Button } from "@/components/ui/button"

export function LandingDetails({ onGetStarted }: { onGetStarted: () => void }) {
  return <div className="bg-bg-base px-8 pb-24 md:px-16 lg:px-20">
    <section id="how-it-works" className="mx-auto max-w-7xl border-t border-black/10 py-20">
      <p className="text-[10px] font-semibold uppercase tracking-[.2em] text-zinc-500">Three-agent analysis</p>
      <p className="mt-4 max-w-2xl text-sm leading-7 text-zinc-500">READER, CHECKER, and EXPLAINER each have one bounded role. They never set the verdict: deterministic code applies the final decision rules.</p>
      <div className="mt-8 grid gap-4 md:grid-cols-3">
        {[{ icon: FileSearch, title: "READER", text: "Extracts visible names, dates, court details, demands, and deadlines without judging the letter." }, { icon: Scale, title: "CHECKER", text: "Investigates court records and approved warning-signal sources without deciding the verdict." }, { icon: ShieldCheck, title: "EXPLAINER", text: "Turns the verdict already decided by code into clear language, limitations, and a safer next step." }].map(({ icon: Icon, title, text }, index) => <article className="rounded-[28px] border border-black/5 bg-white/55 p-6 backdrop-blur-xl" key={title}><div className="flex items-center justify-between"><span className="grid size-10 place-items-center rounded-full bg-brand-soft"><Icon size={17} /></span><span className="text-xs text-zinc-400">0{index + 1}</span></div><h2 className="mt-8 font-display text-2xl tracking-[-.04em]">{title}</h2><p className="mt-3 text-sm leading-6 text-zinc-500">{text}</p></article>)}
      </div>
    </section>

    <section id="evidence" className="mx-auto grid max-w-7xl gap-8 border-t border-black/10 py-20 md:grid-cols-2 md:items-end">
      <div><p className="text-[10px] font-semibold uppercase tracking-[.2em] text-zinc-500">Evidence, not certainty theater</p><h2 className="mt-5 max-w-2xl font-display text-4xl tracking-[-.055em] sm:text-6xl">A court-record match does not prove a letter is authentic.</h2></div>
      <div><p className="max-w-lg text-sm leading-7 text-zinc-500">Served separates extracted facts, external checks, warning signals, and limitations. If a source is unavailable or evidence conflicts, the result should say so plainly.</p><Button onClick={onGetStarted} className="mt-6">Start an analysis <ArrowUpRight size={15} /></Button></div>
    </section>

    <section id="privacy" className="mx-auto max-w-7xl rounded-[32px] border border-black/5 bg-white/55 p-8 backdrop-blur-xl sm:p-12"><span className="inline-flex rounded-full bg-brand-soft px-3 py-1 text-[10px] font-semibold uppercase tracking-[.2em]">Privacy</span><h2 className="mt-5 max-w-2xl font-display text-4xl tracking-[-.05em]">Clear handling, clear limits.</h2><p className="mt-4 max-w-2xl text-sm leading-7 text-black/60">Uploaded file bytes are processed to produce the analysis. The workspace saves analysis metadata and results to your signed-in account. Served is an evidence tool, not a substitute for a lawyer or an official court notice.</p></section>

    <section id="resources" className="mx-auto grid max-w-7xl gap-10 border-b border-black/10 py-20 md:grid-cols-2"><div><p className="text-[10px] font-semibold uppercase tracking-[.2em] text-zinc-500">Need human help?</p><h2 className="mt-4 font-display text-4xl tracking-[-.05em]">Use independently sourced official channels.</h2><p className="mt-3 max-w-xl text-sm leading-6 text-zinc-500">Contact the court using its official website or ask a qualified attorney to review urgent or high-stakes correspondence.</p><Button variant="outline" onClick={onGetStarted} className="mt-6">Open your workspace →</Button></div><Accordion type="single" collapsible className="rounded-[28px] border border-black/5 bg-white/55 px-6 backdrop-blur-xl"><AccordionItem value="record-match"><AccordionTrigger>Does a court-record match prove authenticity?</AccordionTrigger><AccordionContent className="leading-6 text-zinc-500">No. It only shows that related case information exists in the checked source. The letter and its contact details still require independent review.</AccordionContent></AccordionItem><AccordionItem value="unavailable"><AccordionTrigger>What if a source is unavailable?</AccordionTrigger><AccordionContent className="leading-6 text-zinc-500">Served reports the check as unavailable instead of treating it as a failed match or a warning signal.</AccordionContent></AccordionItem><AccordionItem value="legal-advice" className="border-b-0"><AccordionTrigger>Is this legal advice?</AccordionTrigger><AccordionContent className="leading-6 text-zinc-500">No. Served organizes evidence and limitations. Urgent, ambiguous, or high-stakes letters should be reviewed by a qualified professional.</AccordionContent></AccordionItem></Accordion></section>
  </div>
}
